apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 4
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: app
        image: ahmedo42/capstone-project:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080